package app

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestShellWritesAppConfigAndRunsIsolatedTmux(t *testing.T) {
	t.Setenv("TMUX", "/tmp/default-tmux")

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/proj mux/bin/projmux", nil },
		lookupEnv: func(name string) string {
			if name == "HOME" {
				return home
			}
			if name == "XDG_CONFIG_HOME" {
				return ""
			}
			return os.Getenv(name)
		},
		homeDir:    func() (string, error) { return home, nil },
		getwd:      func() (string, error) { return "/tmp/work tree", nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}

	if err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	configPath := filepath.Join(home, ".config", "projmux", "tmux.conf")
	content, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatal(err)
	}
	config := string(content)
	for _, want := range []string{
		"Generated by projmux. Used by `projmux shell`.",
		"set -g @projmux_app 1",
		"set -g history-limit 10000",
		"set -g set-clipboard on",
		"set -g default-shell /usr/bin/zsh",
		"set -ga update-environment \"WSL_DISTRO_NAME\"",
		"set -g pane-border-status top",
		"set -s user-keys[7] \"\\033[9008u\"",
		"bind-key -n C-n new-window -c \"#{pane_current_path}\"",
		"bind-key -n M-r command-prompt",
		"bind-key -n User8 previous-window",
		"bind-key -n User9 next-window",
		"bind-key -n User10 command-prompt",
		"bind-key -n User11 command-prompt",
		"set -g status-left-length 20",
		"set -g status-left \"#[bold,fg=colour231,bg=colour33] #{b:pane_current_path} #[default]\"",
		"#[bold,fg=colour231,bg=colour33] #{b:pane_current_path} #[default]",
		"'/tmp/proj mux/bin/projmux' tmux popup-toggle --client #{client_tty} sessionizer-sidebar",
	} {
		if !strings.Contains(config, want) {
			t.Fatalf("config = %q, want substring %q", config, want)
		}
	}
	if strings.Contains(config, "#[bold,fg=colour16,bg=colour45] app #[default]") {
		t.Fatalf("config = %q, did not expect duplicate app status badge", config)
	}

	wantArgs := []string{"-L", "projmux", "-f", configPath, "new-session", "-A", "-s", "main", "-c", "/tmp/work tree"}
	if recorder.name != "tmux" || !reflect.DeepEqual(recorder.args, wantArgs) {
		t.Fatalf("command = %s %#v, want tmux %#v", recorder.name, recorder.args, wantArgs)
	}
	for _, env := range recorder.env {
		if strings.HasPrefix(env, "TMUX=") {
			t.Fatalf("runner env contains TMUX: %#v", recorder.env)
		}
	}
}

func TestShellSupportsRuntimeOverrides(t *testing.T) {
	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  func(string) string { return "" },
		homeDir:    func() (string, error) { return home, nil },
		getwd:      func() (string, error) { return "", nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}
	configPath := filepath.Join(home, "custom.conf")
	args := []string{"--socket", "pmx-dev", "--session", "dev", "--config", configPath, "--bin", "/opt/projmux", "--no-install"}
	if err := cmd.Run(args, &bytes.Buffer{}, &bytes.Buffer{}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if _, err := os.Stat(configPath); !os.IsNotExist(err) {
		t.Fatalf("config was written despite --no-install: %v", err)
	}
	wantArgs := []string{"-L", "pmx-dev", "-f", configPath, "new-session", "-A", "-s", "dev"}
	if recorder.name != "tmux" || !reflect.DeepEqual(recorder.args, wantArgs) {
		t.Fatalf("command = %s %#v, want tmux %#v", recorder.name, recorder.args, wantArgs)
	}
}

func TestShellRejectsNestedProjmuxSocket(t *testing.T) {
	t.Setenv("TMUX", "/tmp/tmux-1000/projmux,123,0")

	home := t.TempDir()
	recorder := &recordingShellRunner{}
	cmd := &shellCommand{
		executable: func() (string, error) { return "/tmp/projmux", nil },
		lookupEnv:  os.Getenv,
		homeDir:    func() (string, error) { return home, nil },
		getwd:      func() (string, error) { return "", nil },
		writeFile:  os.WriteFile,
		runCommand: recorder.run,
	}

	err := cmd.Run(nil, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil {
		t.Fatal("expected nested shell error")
	}
	if !strings.Contains(err.Error(), "cannot run inside") {
		t.Fatalf("error = %v, want nested shell guard", err)
	}
	if recorder.name != "" {
		t.Fatalf("tmux command ran despite nested guard: %s %#v", recorder.name, recorder.args)
	}
	configPath := filepath.Join(home, ".config", "projmux", "tmux.conf")
	if _, err := os.Stat(configPath); !os.IsNotExist(err) {
		t.Fatalf("config was written despite nested guard: %v", err)
	}
}

func TestShellRejectsNestedCustomSocket(t *testing.T) {
	t.Setenv("TMUX", "/tmp/tmux-1000/pmx-dev,123,0")

	cmd := &shellCommand{lookupEnv: os.Getenv}
	err := cmd.Run([]string{"--socket", "pmx-dev"}, &bytes.Buffer{}, &bytes.Buffer{})
	if err == nil {
		t.Fatal("expected nested custom socket error")
	}
	if !strings.Contains(err.Error(), `"pmx-dev"`) {
		t.Fatalf("error = %v, want socket name", err)
	}
}

func TestShellRejectsInvalidUsage(t *testing.T) {
	t.Parallel()

	var stderr bytes.Buffer
	err := (&shellCommand{}).Run([]string{"extra"}, &bytes.Buffer{}, &stderr)
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "shell does not accept positional arguments") {
		t.Fatalf("error = %v", err)
	}
	if !strings.Contains(stderr.String(), "Usage:") {
		t.Fatalf("stderr = %q, want usage", stderr.String())
	}
}

type recordingShellRunner struct {
	env  []string
	name string
	args []string
}

func (r *recordingShellRunner) run(_ context.Context, env []string, name string, args ...string) error {
	r.env = append([]string(nil), env...)
	r.name = name
	r.args = append([]string(nil), args...)
	return nil
}
